# lextab.py. This file automatically created by PLY (version 3.4). Don't edit!
_tabversion   = '3.4'
_lextokens    = {'RENAME': 1, 'NOTEQUAL': 1, 'DIVIDE': 1, 'RETURN': 1, 'LPAREN': 1, 'PREPARE': 1, 'THEN': 1, 'RETURNASSIGN': 1, 'EXPLAIN': 1, 'IN': 1, 'EQUAL': 1, 'WHILE': 1, 'HELP': 1, 'BEGIN': 1, 'DESCRIBE': 1, 'MINUS': 1, 'DOT': 1, 'STRING': 1, 'INSERT': 1, 'BETWEEN': 1, 'SET': 1, 'RPAREN': 1, 'TRUNCATE': 1, 'CREATE': 1, 'DROP': 1, 'ALTER': 1, 'LT': 1, 'PLUS': 1, 'SELECT': 1, 'COMMA': 1, 'USE': 1, 'EXECUTE': 1, 'GT': 1, 'END': 1, 'GTE': 1, 'FOR': 1, 'SHOW': 1, 'INTO': 1, 'UPDATE': 1, 'TIMES': 1, 'ELSEIF': 1, 'DELIMITER': 1, 'LTE': 1, 'INTEGER': 1, 'ELSE': 1, 'WHERE': 1, 'IF': 1, 'AND': 1, 'FROM': 1, 'NAME': 1, 'STDNOTEQUALOR': 1, 'FLOAT': 1, 'AS': 1, 'DO': 1, 'CALL': 1, 'NOT': 1, 'DELETE': 1, 'INFILE': 1, 'MOD': 1}
_lexreflags   = 0
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_newline>\\n+)|(?P<t_COMMENT>/\\*[\\d\\D]*?\\*/|//.*\\n|--.*\\n)|(?P<t_STRING>\\"([^\\"]|\\"\\"|\\\\\\")*\\"|\'([^\']|\'\'|\\\\\')*\'|`(``|[^`])*`)|(?P<t_INTEGER>\\b[0-9]\\d*\\b)|(?P<t_FLOAT>\\b\\d+\\.\\d+\\b)|(?P<t_RETURNASSIGN>\\:\\=)|(?P<t_LTE>\\<\\=)|(?P<t_STDNOTEQUAL>\\<\\>)|(?P<t_GTE>\\>\\=)|(?P<t_LPAREN>\\()|(?P<t_MINUS>\\-)|(?P<t_PLUS>\\+)|(?P<t_EQUAL>\\=)|(?P<t_GT>\\>)|(?P<t_LT>\\<)|(?P<t_DOT>\\.)|(?P<t_NOTEQUAL>!=)|(?P<t_RPAREN>\\))|(?P<t_DIVIDE>\\/)|(?P<t_MOD>%)|(?P<t_COMMA>,)|(?P<t_DELIMITER>;)', [None, ('t_newline', 'newline'), ('t_COMMENT', 'COMMENT'), ('t_STRING', 'STRING'), None, None, None, ('t_INTEGER', 'INTEGER'), ('t_FLOAT', 'FLOAT'), (None, 'RETURNASSIGN'), (None, 'LTE'), (None, 'STDNOTEQUAL'), (None, 'GTE'), (None, 'LPAREN'), (None, 'MINUS'), (None, 'PLUS'), (None, 'EQUAL'), (None, 'GT'), (None, 'LT'), (None, 'DOT'), (None, 'NOTEQUAL'), (None, 'RPAREN'), (None, 'DIVIDE'), (None, 'MOD'), (None, 'COMMA'), (None, 'DELIMITER')])]}
_lexstateignore = {'INITIAL': ''}
_lexstateerrorf = {'INITIAL': None}
